federation_version: =2.9.0
subgraphs:
  products:
    routing_url: http://localhost:7000
    schema:
      file: ./products.graphql
  users:
    routing_url: http://localhost:8000
    schema:
      file: ./users.graphql